#GetSystemInfo vars
set(GET_SYSTEM_INFO_ROOT_DIR_NAME "GetSystemInfo")
set(GET_SYSTEM_INFO_ROOT_PATH "./${GET_SYSTEM_INFO_ROOT_DIR_NAME}")
#


#AE plugin vars
set(AE_ROOT_DIR_NAME "LL_AE")
set(AE_ROOT_PATH "${AE_ROOT_DIR_NAME}")
#end AV plugin vars

#AV plugin vars
set(AV_ROOT_DIR_NAME "LL_AV")
set(AV_ROOT_PATH "${AV_ROOT_DIR_NAME}")
#end AV plugin vars


#AW plugin vars
set(AW_ROOT_DIR_NAME "LL_AW")
set(AW_ROOT_PATH "${AW_ROOT_DIR_NAME}")

#end AW plugin vars

#HIPS plugin vars
set(HIPS_ROOT_DIR_NAME "LL_HIPS")
set(HIPS_ROOT_PATH "${HIPS_ROOT_DIR_NAME}")
#end HIPS plugin vars

#OS plugin vars
set(OS_ROOT_DIR_NAME "LL_OS")
set(OS_ROOT_PATH "${OS_ROOT_DIR_NAME}")

#end OS plugin vars

#OSPH plugin vars
set(OSPH_ROOT_DIR_NAME "LL_OSPH")
set(OSPH_ROOT_PATH "${OSPH_ROOT_DIR_NAME}")

#end OSPH plugin vars


#Pth plugin vars
set(PTH_ROOT_DIR_NAME "LL_PtH_And_Credentials")
set(PTH_ROOT_PATH "${PTH_ROOT_DIR_NAME}")
#end pth plugin vars


set(AE_PLUGIN_PAYLOAD_HOME "${CMAKE_CURRENT_SOURCE_DIR}/${AE_ROOT_PATH}/LL_AE/LL_AE/payload/")
if(NOT EXISTS ${AE_PLUGIN_PAYLOAD_HOME})
	file(MAKE_DIRECTORY ${AE_PLUGIN_PAYLOAD_HOME})
endif()

set(AV_PLUGIN_PAYLOAD_HOME "${CMAKE_CURRENT_SOURCE_DIR}/${AV_ROOT_PATH}/LL_AV/LL_AV/payload/")
if(NOT EXISTS ${AV_PLUGIN_PAYLOAD_HOME})
	file(MAKE_DIRECTORY ${AV_PLUGIN_PAYLOAD_HOME})
endif()

set(AW_PLUGIN_PAYLOAD_HOME "${CMAKE_CURRENT_SOURCE_DIR}/${AW_ROOT_PATH}/LL_AW/LL_AW/payload/")
if(NOT EXISTS ${AW_PLUGIN_PAYLOAD_HOME})
	file(MAKE_DIRECTORY ${AW_PLUGIN_PAYLOAD_HOME})
endif()

set(HIPS_PLUGIN_PAYLOAD_HOME "${CMAKE_CURRENT_SOURCE_DIR}/${HIPS_ROOT_PATH}/LL_HIPS/LL_HIPS/payload/")
if(NOT EXISTS ${HIPS_PLUGIN_PAYLOAD_HOME})
	file(MAKE_DIRECTORY ${HIPS_PLUGIN_PAYLOAD_HOME})
endif()

set(OS_PLUGIN_PAYLOAD_HOME "${CMAKE_CURRENT_SOURCE_DIR}/${OS_ROOT_PATH}/LL_OS/LL_OS/payload/")
if(NOT EXISTS ${OS_PLUGIN_PAYLOAD_HOME})
	file(MAKE_DIRECTORY ${OS_PLUGIN_PAYLOAD_HOME})
endif()

set(OSPH_PLUGIN_PAYLOAD_HOME "${CMAKE_CURRENT_SOURCE_DIR}/${OSPH_ROOT_PATH}/LL_OSPH/LL_OSPH/payload/")
if(NOT EXISTS ${OSPH_PLUGIN_PAYLOAD_HOME})
	file(MAKE_DIRECTORY ${OSPH_PLUGIN_PAYLOAD_HOME})
endif()

set(PTH_PLUGIN_PAYLOAD_HOME "${CMAKE_CURRENT_SOURCE_DIR}/${PTH_ROOT_PATH}/LL_PtH/LL_PtH/payload/")
if(NOT EXISTS ${PTH_PLUGIN_PAYLOAD_HOME})
	file(MAKE_DIRECTORY ${PTH_PLUGIN_PAYLOAD_HOME})
endif()




